import { PageShell, StubNotice } from "@/components/Shell";

export const metadata = { title: "Reports" };

export default function AdminReportsPage() {
  return (
    <PageShell
      title="Reports"
      subtitle="Candidate, exam, band distribution, writing, attendance — export PDF/Excel."
    >
      <StubNotice feature="Reports (generated by the worker)" />
    </PageShell>
  );
}
